// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Airlines.Persistence.Entities;

public partial class Airline
{
    [Key]
    public int AirlineId { get; set; }

    [Required]
    [StringLength(6)]
    public string Name { get; set; }

    public DateOnly Founded { get; set; }

    public int FleetSize { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string Description { get; set; }
}