// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Airlines.Persistence.Entities;

[Index("Code", Name = "UQ__Airports__A25C5AA77AA8471F", IsUnique = true)]
public partial class Airport
{
    [Key]
    [StringLength(3)]
    public string AirportId { get; set; }

    [Required]
    [StringLength(255)]
    public string Name { get; set; }

    [Required]
    [StringLength(75)]
    public string Country { get; set; }

    [Required]
    [StringLength(100)]
    public string City { get; set; }

    [Required]
    [StringLength(3)]
    public string Code { get; set; }

    public int Runways { get; set; }

    public DateOnly Founded { get; set; }

    [InverseProperty("ArrivalAirport")]
    public virtual ICollection<Flight> FlightArrivalAirports { get; set; } = new List<Flight>();

    [InverseProperty("DepartureAirport")]
    public virtual ICollection<Flight> FlightDepartureAirports { get; set; } = new List<Flight>();
}