// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Airlines.Persistence.Entities;

public partial class Flight
{
    [Key]
    public int FlightId { get; set; }

    [Required]
    [StringLength(5)]
    public string Number { get; set; }

    public int? DepartureAirportId { get; set; }

    public int? ArrivalAirportId { get; set; }

    public DateTime DepartureDateTime { get; set; }

    public DateTime ArrivalDateTime { get; set; }

    [ForeignKey("ArrivalAirportId")]
    [InverseProperty("FlightArrivalAirports")]
    public virtual Airport ArrivalAirport { get; set; }

    [ForeignKey("DepartureAirportId")]
    [InverseProperty("FlightDepartureAirports")]
    public virtual Airport DepartureAirport { get; set; }
}