stages:
- build
- test

image: mcr.microsoft.com/dotnet/sdk:8.0

build_job:
 stage: build
 script:
  - 'dotnet restore'
  - 'dotnet build -warnaserror'

xunit_test:
  stage: test
  script:
    - 'dotnet restore'
    - 'dotnet test --verbosity normal --logger "trx;LogFileName=test_results.xml" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./TestResults/ /p:Threshold=30 /p:ThresholdType=line /p:ThresholdStat=total'
  coverage: '/Total\s*\|\s*(\d+(?:\.\d+)?)/'
  artifacts:
    paths:
      - ./Airlines.UnitTest/TestResults/*.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: './Airlines.UnitTest/TestResults/coverage.cobertura.xml'
