// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage("Style", "IDE0057:Use range operator", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Business.Utilities.StringHelper.SplitBeforeLastElement(System.String)~System.String[]")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Business.Commands.CommandInvoker.ExecuteCommand(Airlines.Business.Commands.ICommand)")]
[assembly: SuppressMessage("Style", "IDE0305:Simplify collection initialization", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Business.Commands.CommandClient.ProcessCommand(System.String,System.Boolean)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Business.Mapping.ObjectMapper.MapToAirport(System.String)~Airlines.Business.Models.Airport")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Business.Mapping.ObjectMapper.MapToAirline(System.String)~Airlines.Business.Models.Airline")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Business.InputValidator.ValidateAircraftData(System.String)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Business.Mapping.ObjectMapper.MapToFlight(System.String)~Airlines.Business.Models.Flight")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Business.Mapping.ObjectMapper.MapToCargoAircraft(System.String)~Airlines.Business.Models.Aircrafts.CargoAircraft")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Business.Mapping.ObjectMapper.MapToPrivateAircraft(System.String)~Airlines.Business.Models.Aircrafts.PrivateAircraft")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Business.Mapping.ObjectMapper.MapToPassengerAircraft(System.String)~Airlines.Business.Models.Aircrafts.PassengerAircraft")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Business.InputValidator.ValidateRouteData(System.String)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Business.InputValidator.ContainsOnlyLettersAndSpaces(System.String)~System.Boolean")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Business.InputValidator.ContainsOnlyLettersOrDigits(System.String)~System.Boolean")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Business.Validation.CommandValidator.ValidateCargoReservation(Airlines.Business.Models.Reservations.CargoReservation,Airlines.Business.Models.Aircrafts.CargoAircraft)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Business.Validation.CommandValidator.ValidateTicketReservation(Airlines.Business.Models.Reservations.TicketReservation,Airlines.Business.Models.Aircrafts.PassengerAircraft)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Business.Validation.CommandValidator.ValidateCommandArguments(System.String)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Business.Validation.CommandValidator.ValidateSearchCommand(System.String)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Business.Validation.CommandValidator.ValidateSortCommand(System.String,System.String)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Business.Validation.CommandValidator.ValidateExistCommand(System.String)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Business.Validation.CommandValidator.ValidateListCommand(System.String,System.String)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Business.Managers.RouteManager.GetNextAirport(System.Collections.Generic.Dictionary{Airlines.Business.Models.Airport,System.Double},System.Collections.Generic.HashSet{Airlines.Business.Models.Airport})~Airlines.Business.Models.Airport")]
