// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Airlines.Persistence.Configuration;

namespace Airlines.Persistence.Entities;

public partial class AirlinesDBContext : DbContext
{
    public AirlinesDBContext()
    {
    }

    public AirlinesDBContext(DbContextOptions<AirlinesDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Airline> Airlines { get; set; }

    public virtual DbSet<Airport> Airports { get; set; }

    public virtual DbSet<Flight> Flights { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            var connection = ConfigurationManager.GetConnectionString("Home");
            optionsBuilder.UseSqlServer(connection);
        }

    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Airline>(entity =>
        {
            entity.HasKey(e => e.AirlineId).HasName("PK__Airlines__DC45821363676EB6");
        });

        modelBuilder.Entity<Airport>(entity =>
        {
            entity.HasKey(e => e.AirportId).HasName("PK__Airports__E3DBE0EAAB060750");
        });

        modelBuilder.Entity<Flight>(entity =>
        {
            entity.HasKey(e => e.FlightId).HasName("PK__Flights__8A9E14EE3C9C1F5B");

            entity.HasOne(d => d.ArrivalAirport).WithMany(p => p.FlightArrivalAirports).HasConstraintName("FK__Flights__Arrival__6BE40491");

            entity.HasOne(d => d.DepartureAirport).WithMany(p => p.FlightDepartureAirports).HasConstraintName("FK__Flights__Departu__6AEFE058");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}