// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "<Pending>")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Web.Api.Controllers.AirlinesController.GetOne(System.Int32)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{Airlines.Service.Dto.AirlineDto}}")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Web.Api.Controllers.AirlinesController.GetAll~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{System.Collections.Generic.List{Airlines.Service.Dto.AirlineDto}}}")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Web.Api.Controllers.AirportsController.GetAll~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{System.Collections.Generic.List{Airlines.Service.Dto.AirportDto}}}")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Web.Api.Controllers.AirportsController.GetOne(System.Int32)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{Airlines.Service.Dto.AirportDto}}")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Web.Api.Controllers.FlightsController.GetAll~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{System.Collections.Generic.List{Airlines.Service.Dto.FlightDto}}}")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Web.Api.Controllers.FlightsController.GetOne(System.Int32)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{Airlines.Service.Dto.FlightDto}}")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Web.Api.Controllers.AirportsController.Delete(System.Int32)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{Airlines.Service.Dto.AirportDto}}")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Web.Api.Controllers.AirlinesController.Delete(System.Int32)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{Airlines.Service.Dto.AirlineDto}}")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Web.Api.Controllers.FlightsController.Delete(System.Int32)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{Airlines.Service.Dto.FlightDto}}")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Web.Api.Controllers.AirlinesController.Update(Airlines.Service.Dto.AirlineDto)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{Airlines.Service.Dto.AirlineDto}}")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Web.Api.Controllers.AirportsController.Update(Airlines.Service.Dto.AirportDto)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{Airlines.Service.Dto.AirportDto}}")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.Web.Api.Controllers.FlightsController.Update(Airlines.Service.Dto.FlightDto)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{Airlines.Service.Dto.FlightDto}}")]
