// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0022:Use expression body for method", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.UnitTests.ConsoleTests.ValidateAirportDataTests.ValidateAirportData_InvalidIdLength_ThrowsInvalidIdLengthException(System.String)")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for method", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.UnitTests.ConsoleTests.ValidateAirportDataTests.ValidateAirportData_InvalidIdCharacters_ThrowsInvalidIdCharactersException(System.String)")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for method", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.UnitTests.ConsoleTests.ValidateAirportDataTests.ValidateAirportData_InvalidNameCharacters_ThrowsInvalidAirportNameException(System.String)")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for method", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.UnitTests.ConsoleTests.ValidateAirportDataTests.ValidateAirportData_InvalidCity_ThrowsInvalidAirportCityException(System.String)")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for method", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.UnitTests.ConsoleTests.ValidateAirportDataTests.ValidateAirportData_InvalidCountry_ThrowsInvalidAirportCountryException(System.String)")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for method", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.UnitTests.ConsoleTests.ValidateAirportDataTests.ValidateAirportData_DuplicateIds_ThrowsDuplicateIdException(System.String[])")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for method", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.UnitTests.ConsoleTests.ValidateAirlineDataTests.ValidateAirlineData_InvalidIdLength_ThrowsInvalidIdLengthException(System.String)")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for method", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.UnitTests.ConsoleTests.ValidateAirlineDataTests.ValidateAirlineData_InvalidIdCharacters_ThrowsInvalidIdCharactersException(System.String)")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for method", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.UnitTests.ConsoleTests.ValidateAirlineDataTests.ValidateAirlineData_InvalidNameCharacters_ThrowsInvalidAirportNameException(System.String)")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for method", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.UnitTests.ConsoleTests.ValidateAirlineDataTests.ValidateAirlineData_DuplicateIds_ThrowsDuplicateIdException(System.String[])")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for method", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.UnitTests.ConsoleTests.ValidateFlightDataTests.ValidateFlightData_InvalidIdLength_ThrowsInvalidIdLengthException(System.String)")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for method", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.UnitTests.ConsoleTests.ValidateFlightDataTests.ValidateFlightData_InvalidIdCharacters_ThrowsInvalidIdCharactersException(System.String)")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for method", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.UnitTests.ConsoleTests.ValidateFlightDataTests.ValidateFlightData_InvalidNameCharacters_ThrowsInvalidAirportNameException(System.String)")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for method", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.UnitTests.ConsoleTests.ValidateFlightDataTests.ValidateFlightData_InvalidCity_ThrowsInvalidAirportCityException(System.String)")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for method", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.UnitTests.ConsoleTests.ValidateFlightDataTests.ValidateFlightData_DuplicateIds_ThrowsDuplicateIdException(System.String[])")]
[assembly: SuppressMessage("Style", "IDE0022:Use expression body for method", Justification = "<Pending>", Scope = "member", Target = "~M:Airlines.UnitTests.ConsoleTests.ValidateAircraftDataTests.ValidateAircraftData_InvalidNameCharacters_ThrowsInvalidAirportNameException(System.String)")]
